#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=64G
#SBATCH --job-name=21cmvFAST_lightcone
#SBATCH --time=12:00:00
#SBATCH --output=/scratch/s4950836/%j.out

module purge
module load GCC
module load GSL
module load foss/2022b
module load FFTW
module load Python

srun export LC_ALL=C

srun make
srun ./init 1.000000 1.000000
srun ./create_dens_boxes_for_LC 1.000000 1.000000 6.0
srun ./drive_21cmMC_streamlined 1.000000 1.000000 1 1 0 6.0
# srun python ./21CMMC.py